#!/bin/bash

# bordersの設定
# アクティブウィンドウにボーダーを表示する

options=(
  style=round        # round | square
  width=6.0          # ボーダーの太さ
  hidpi=on           # Retina対応
  active_color=0xffa7c080   # アクティブウィンドウのボーダー色 (Everforest green)
  inactive_color=0x00000000 # 非アクティブは透明
)

borders "${options[@]}"
